# Generated by Django 3.1.1 on 2020-10-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('title',)},
        ),
    ]
